###Numpy Homework

Q1.Score: 5/5

Create a all zeros array of size 10 and set it in the variable called “arr1”.

In [ ]:
# Your answer
import numpy as np
arr1 = np.zeros(10, dtype = int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Score: 5

Excellent!

Q2. Score: 5/5

Create a 1D array of numbers from 0 to 9 and set it in the variable called “arr2”.

In [ ]:
# Your answer
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Score: 5

Excellent!

Q3. Score: 10/10

Create a 3x3x3 array with random values and set it in the variable called “arr3”.
Print arr3.

Print the value in the center of the array using indexing.

In [ ]:
# Your answer
arr3 = np.random.random((3, 3, 3))
arr3

array([[[0.01992918, 0.88387367, 0.08511999],
        [0.27263074, 0.78033597, 0.86314222],
        [0.07416608, 0.24453553, 0.40619319]],

       [[0.27122021, 0.95391739, 0.8701483 ],
        [0.60261041, 0.94913811, 0.50037348],
        [0.9372712 , 0.00104931, 0.79796347]],

       [[0.39108713, 0.36265735, 0.89709551],
        [0.09444832, 0.77221188, 0.91390045],
        [0.9883674 , 0.25247424, 0.00427166]]])

Score: 7

It should be (3,3,3)

### CCC Contest Questions

Please solve the question 3 - Cold compress
(Score: 20/20) 


(Page 7 in https://www.cemc.uwaterloo.ca/contests/computing/past_ccc_contests/2019/stage%201/juniorEF.pdf)

In [ ]:
# Your answer

# Time Consumed: 39 minutes 06 seconds
N = int(input("Input N: "))
lines = []
for i in range(N):
  line = input()
  lines.append(line)

for line in lines:
  count = 0
  message = ""
  for j in range(len(line)):
    if j != len(line) - 1 and line[j] == line[j + 1]:
      count += 1
    else:
      message += str(count + 1) + " " + line[j] + " "
      count = 0
  print(message.strip()) 

Input N: 1
####____!!!!####
4 # 4 _ 4 ! 4 #


score: 15/20

You can check the special case I put above. The answer is incorrect.
Try to come up with another way to solve this instead of using the build-in count method.

In [ ]:
n = int(input()) 
lines = []

for i in range(n):
  line = input()
  lines.append(line)

for i in range(n):
  # 0123456789
  # +++===!!!!
  # 3 + 3 = 4 !

  count = 0
  encoded_line = ""
  line = lines[i] # current line needs to be encoded

  for j in range(len(line)): # go through each character of the current line
    if j != len(line) -1 and line[j] == line[j+1]: #some corner case
      count += 1
    else:
      # we update the encoded_line
      encoded_line += str(count + 1) + " " + line[j] + " "
      count = 0
  print(encoded_line)

1
+++===!!!!
3 + 3 = 4 ! 
