#Numpy Basics

### Create Numpy Arrays

####First way: create Numpy Arrays from Lists

In [9]:
import numpy as np
arr1 = np.array([1,2,3,4])

print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
lst = [1,2,3,4]

print(lst)
print(type(lst))

[1, 2, 3, 4]
<class 'list'>


In [11]:
# We can explicitly set the data type of the array
arr2 = np.array([1,2,3,4], dtype='float32')

print(arr2)
print(type(arr2))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [13]:
# Creat a 2d array from a list of lists
lists = [[0,1,2],[3,4,5],[6,7,8]]
arr2d = np.array(lists)

print(lists)
print(arr2d)
print(type(arr2d))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [19]:
# What's the difference between array and list
print(arr1)
print(lst)

[1 2 3 4]
[1, 2, 3, 4]


In [ ]:
# 1st difference: We can do Vector (element-wise) operations to array
print(lst * 2) # it will duplicate and extend the current list
print(lst + 2) # it's an error
print(lst * lst) # it's an error

In [23]:
print(arr1 * 2)
print(arr1 + 2)
print(arr1 * arr1)

[2 4 6 8]
[3 4 5 6]
[ 1  4  9 16]


In [35]:
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2d_another = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d_another)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(arr2d * arr2d)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [37]:
print(arr2d * arr2d_another)

[[ 0  2  6]
 [12 20 30]
 [42 56 72]]


In [47]:
# 2nd difference: elements in array has to be the same dtype
lst_has_lots_of_stuff = [1,0.9,False,"Apple"]
d = np.array(lst_has_lots_of_stuff) # something you should not do!
print(d)
print(d.dtype)

['1' '0.9' 'False' 'Apple']
<U32


In [ ]:
# 3rd difference: array and list with same items, numpy array will take much less space than Python list

####Second way: create arrays from functions

In [ ]:
# create an int array filled with zeros, length is 10
np.zeros(100, dtype=int)

In [ ]:
# create a 3 x 4 float array filled with ones
np.ones((3,4), dtype=float) 

In [48]:
# create an array with numbers from 0 to 20, step is 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
# create an array of 20 values evenly spaced between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [57]:
# create a 3 x 3 array of uniformly distributed random values btween 0 and 1
np.random.random((3,3))

array([[0.14047042, 0.29722963, 0.07025022],
       [0.47291832, 0.65982632, 0.6187286 ],
       [0.02197483, 0.63337761, 0.04911519]])

In [63]:
# create a 3 x 3 array of random int btween 0 and 10 (10 is not included)
np.random.randint(0,10,(3,3))

array([[2, 8, 3],
       [7, 2, 3],
       [1, 6, 6]])

In [64]:
# create an int array of random numbers btween 0 and 10 (10 is not included), length is 6
np.random.randint(0,10,6)

array([5, 8, 4, 3, 3, 6])

###Array Attributes

In [ ]:
arr1d = np.array([0,1,2,3,4])
arr2d = np.array([[0,1,2],[3,4,5]], dtype = 'float32')
print(arr1d)
print(arr2d)

In [ ]:
# data type of the array
print("dtype:", arr1d.dtype)
print("dtype:", arr2d.dtype)
# the number of dimenstions
print("ndim:", arr1d.ndim)
print("ndim:", arr2d.ndim)
# the size of the array (the number of elements)
print("size:", arr1d.size)
print("size:", arr2d.size)
# the shape of the array
print("shape:", arr1d.shape)
print("shape:", arr2d.shape)

### Indexing

In [ ]:
arr1 = np.array([1,2,3,5,5,6,7])
print(arr1[0]) # the first element
print(arr1[4]) # the fifth element
print(arr1[-1]) # the last element
print(arr1[-2]) # the second last element

In [ ]:
arr2 = np.array([[0,1,2],[3,4,5],[9,8,7],[11,12,16]], dtype = 'float32')
print(arr2)
print(arr2[2,1]) # get the value of 8
print(arr2[-2,-2]) # get the value of 8, another way!
# lets update the 7 to 6
arr2[2,2] = 6.0
print(arr2)

In [ ]:
# slicing
x1 = np.arange(10)
print(x1)
# get 0 to 5 (included)
print(x1[:6])
# get the numbers after 6 (included)
print(x1[6:])
# get 5 and 6
print(x1[5:7])
# get all the even numbers
print(x1[::2])
# reverse all elements
print(x1[::-1])

In [ ]:
x2 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x2)
# get the 2nd row
print(x2[1:2,:])
print(x2[1])

# all rows, every other column
print(x2[:,::2])

# reverse all rows
print(x2[::-1,:])

# reverse rows and columns
print(x2[::-1,::-1])

In [ ]:
print(x2) # x2 remains the same
x3 = x2[::-1,:].copy() # x2's changes will not influence x3