## Continue to learn about Numpy


### Reshape

In [ ]:
import numpy as np

arr1 = np.arange(1,10).reshape((3,3))
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([1,2,3])
print(arr2.reshape((1,3)))
print(arr2.reshape((3,1)))

[[1 2 3]]
[[1]
 [2]
 [3]]


### Concatenation

In [ ]:
arr3 = np.array([1,2,3])
arr4 = np.array([3,2,1])
arr5 = [11,11,11]
print(np.concatenate([arr3,arr4,arr5]))

table = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([table,table]))
# concatenate doesn't change the dimension

[ 1  2  3  3  2  1 11 11 11]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
# something good to know
print(np.hstack((arr3,arr4)))
print(np.vstack((arr3,arr4))) # it gonna change the dimension, depends on the original dimension

[1 2 3 3 2 1]
[[1 2 3]
 [3 2 1]]


### Split

In [ ]:
arr6 = np.arange(10)
x, y, z = np.split(arr6,[3,6]) # 3 and 6 are the index!
print(x,y,z)

[0 1 2] [3 4 5] [6 7 8 9]


### Aggregations

In [ ]:
import numpy as np
x = np.random.random(100)
#print(x)
print(np.sum(x))
print(np.mean(x))
print(x.sum()) # another syntax
print(x.mean())
print(x.max())
print(x.min())

50.457657518971615
0.5045765751897161
50.457657518971615
0.5045765751897161
0.9977166226470771
0.004192377645687251


In [ ]:
table = np.random.random((3,4))
print(table)

print(table.sum())
print(table.min())

# if we want to know more about the row/column
print(np.amin(table,axis = 0)) # column
print(np.amin(table,axis = 1)) # row

[[0.62475377 0.03707598 0.35721251 0.92788357]
 [0.51643894 0.3132704  0.5658193  0.90108668]
 [0.61829732 0.60581293 0.36362478 0.95904285]]
6.7903190253595795
0.03707598364318254
[0.51643894 0.03707598 0.35721251 0.90108668]
[0.03707598 0.3132704  0.36362478]


Exercise:

10x10 array with random values, call it arr. 

Find its min, max.

Find its row-wise min.

In [ ]:
arr = np.random.random((10, 10))
print(arr.min())
print(arr.max())

print(np.amin(arr, axis = 1))

0.0005042165343031035
0.9896067720075937
[0.06797596 0.18214059 0.14141289 0.32221089 0.05310707 0.07831736
 0.11836418 0.00050422 0.09071196 0.37817565]


Exercise:
Replace the maximum value in the given arr, with -1

In [ ]:
arr = np.arange(10)
arr[arr == max(arr)] = -1
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])

In [ ]:
arr = np.arange(10)
print(arr.argmax()) # return the index of the max value
arr[arr.argmax()] = -1
arr

9


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])

In [43]:
lst = [[1, 2],
       [3, 4]]
s = input()
for char in s:
  if char == "V":
    """
    temp = lst[0][0]
    lst[0][0] = lst[0][1]
    lst[0][1] = temp
    temp = lst[1][0]
    lst[1][0] = lst[1][1]
    lst[1][1] = temp"""
    temp0 = [lst[0][1], lst[0][0]] ### ***remember*** 
    temp1 = [lst[1][1], lst[1][0]]
    lst[0] = temp0
    lst[1] = temp1
  if char == "H":
    #temp = lst[0]
    #lst[0] = lst[1]
    #lst[1] = temp
    lst[0],lst[1] = lst[1],lst[0] # exchange the value ****remember****

# print has to be exactly the same
for row in lst:
  s = ""
  for ele in row:
    s += str(ele) + " "
  print(s.strip())

HV
4 3
2 1
